Done all the debugging of the compiler from make in mappraiser/src/. Now facing issue with calling mappraiser library due to an undefined reference to plan_execute in mappraiser/lib/libmappraiser.so.